services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.149.0
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.10.3
    container_name: tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml", "-target=all"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.11.1
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - otel-collector
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.4.2
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
    networks:
      - monitoring

  
  node-exporter:
      image: prom/node-exporter:v1.11.1
      container_name: node-exporter
      restart: unless-stopped
      command:
        - '--path.rootfs=/rootfs'
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
      networks:
        - monitoring
      pid: host
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro

networks:
  monitoring:

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:
