apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    basicAuth: false
    jsonData:
      httpMethod: GET

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    isDefault: false
    editable: false
    basicAuth: false
    jsonData:
      httpMethod: GET
    httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: tenant-1|tenant-2
